# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        args: [--config-file=mypy.ini, --ignore-missing-imports]
        additional_dependencies:
          - types-pyyaml
          - types-requests
          - pandas-stubs
          - pydantic

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: pytest-cov
        name: pytest-cov
        entry: uv run pytest --cov=src/databricks_tools --cov-report=term-missing --cov-fail-under=85
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
